name: example/hello

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: go build -o master

      - name: Test
        run: go test ./...

      - name: Deploy to Azure VM
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Copy files to VM
        run: scp -r ./master azureuser@172.172.246.184:/home/azureuser/project

      - name: Restart Backend Service
        run: ssh azureuser@172.172.246.184 'sudo systemctl restart your-backend-service'
